name: Check linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install pre-commit hooks
      run: |
        python -m pip install --upgrade pip
        python -m pip install pre-commit
    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files
