# Publish doc to website on new release (or manual trigger)
name: "docs"

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8'
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install ruptures and dependecies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        python setup.py install
    - name: Run notebooks
      run: |
        jupyter nbconvert --inplace --to notebook --ExecutePreprocessor.kernel_name=python --execute $(find ./docs -name '*.ipynb')
    - name: Build documentation
      run: |
        mkdocs build
    - name: Publish documentation to remote
      uses: selenehyun/gh-push@master
      env:
        GITHUB_TOKEN: ${{ secrets.DOC_PUSHER_ACCESS_TOKEN }}
        COMMIT_FILES: site/*
        REPO_FULLNAME: centre-borelli/ruptures-docs
        BRANCH: master
